hw1: init commit
AntonYermilov/JavaHW pull request #1
Opened 2017-09-08 06:14 UTC by AntonYermilov

2017-09-10 12:54 UTC, jzuken requested changes

2017-09-10 12:54 UTC, jzuken commented on hw1/src/me/eranik/Main.java
> +    public void testHashTable() {
а есть причины не делать этот метод статиком? тогда в main() можно будет просто его вызвать по-человечески

2017-09-10 12:54 UTC, jzuken commented on hw1/src/me/eranik/algorithm/HashTable.java
> + * @author   Anton Yermilov
вот эти штуки с автором, версией и т.п. обычно не пишут, особенно если над проектом работает больше одного человека. кто что написал, можно легко посмотреть в git blame, а эти аннотации только место занимают и требуют усилий по поддержке

2017-09-10 12:54 UTC, jzuken commented on hw1/src/me/eranik/algorithm/LinkedList.java
> +        begin = null;
инициализацию лучше провести сразу при объявлении поля. всё равно в этом конструкторе ничего умного не происходит

2017-09-10 12:54 UTC, jzuken commented on hw1/src/me/eranik/algorithm/LinkedList.java
> +            begin = end = new Node(null, null, obj);
вообще лучше не увлекаться такими составными конструкциями, их сложнее читать и воспринимать

2017-09-10 12:54 UTC, jzuken commented on hw1/src/me/eranik/algorithm/HashTable.java
> +        table = new LinkedList[1];
это я бы тоже совместил с объявлением полей

2017-09-12 19:11 UTC, jzuken requested changes

2017-09-12 19:11 UTC, jzuken commented on hw1/.idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
не, этот файл не надо выкладывать. тут хранятся настройки вашего локального окружения

2017-09-12 19:11 UTC, jzuken commented on hw1/.idea/vcs.xml
> +    <mapping directory="" vcs="svn" />
что, правда svn? :)

2017-09-12 19:16 UTC, AntonYermilov commented on hw1/.idea/vcs.xml
> +    <mapping directory="" vcs="svn" />
С настройками беда :)

2017-09-12 19:19 UTC, AntonYermilov commented on hw1/.idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
fixed

2017-09-16 07:00 UTC, jzuken requested changes

2017-09-16 07:00 UTC, jzuken commented on hw1/.idea/vcs.xml
> +    <mapping directory="" vcs="svn" />
так поправите?

2017-09-16 07:00 UTC, jzuken commented on hw1/src/me/eranik/algorithm/HashTable.java
> +
пустая строчка лишняя

2017-09-16 07:00 UTC, jzuken commented on hw1/src/me/eranik/algorithm/HashTable.java
> +
и тут

2017-09-16 07:00 UTC, jzuken commented on hw1/src/me/eranik/algorithm/HashTable.java
> +            size -= list.size();
зачем так сложно? почему просто всё не обнулить? полная очистка же

2017-09-16 07:00 UTC, jzuken commented on hw1/src/me/eranik/algorithm/HashTable.java
> +        public boolean equals(Object other) {
переопределяете equals(), переопределите и hashCode().
я бы советовал определять equals() как-то так: https://ru.stackoverflow.com/a/2017

2017-09-23 08:34 UTC, jzuken commented on hw1/src/me/eranik/algorithm/LinkedList.java
> -         * Replaces the reference to the next node with the new one
а чего доки пропали?

2017-09-23 09:00 UTC, jzuken requested changes

2017-09-23 09:00 UTC, jzuken commented on hw1/src/me/eranik/algorithm/HashTable.java
> +import java.lang.Object;
его не нужно специально подключать

2017-09-23 09:00 UTC, jzuken commented on hw1/src/me/eranik/algorithm/HashTable.java
> +    private LinkedList[] table = new LinkedList[1];
1 не маловато будет?

2017-09-23 09:00 UTC, jzuken commented on hw1/src/me/eranik/algorithm/HashTable.java
> +            hash += capacity;
а это гарантирует, что оно будет положительное?

2017-09-23 09:00 UTC, jzuken commented on hw1/src/me/eranik/algorithm/HashTable.java
> +        int index = table[hash].indexOf(new Data(key, null));
а чего бы просто не передавать ключ? зачем такие извращения?

2017-09-23 09:00 UTC, jzuken commented on hw1/src/me/eranik/algorithm/LinkedList.java
> +        public Node getPrev() {
раз он внутренний, ему не нужны геттеры-сеттеры, у родительского класса и так будет доступ к его полям

2017-09-23 22:10 UTC, AntonYermilov commented on hw1/src/me/eranik/algorithm/HashTable.java
> +        int index = table[hash].indexOf(new Data(key, null));
Не придумал, как реализовать это иначе.
У меня так выходит, что LinkedList хранит произвольный объект. И, соответственно, он может пользоваться только методом equals. Непонятно, как это разрешить, передавая один лишь ключ...

2017-09-23 22:10 UTC, AntonYermilov commented on hw1/src/me/eranik/algorithm/HashTable.java
> +    private LinkedList[] table = new LinkedList[1];
Почему, казалось бы, и нет?
Надо будет -- перестроит всё равно.
Но ладно, можно и чуть побольше сделать.

2017-09-25 04:56 UTC, jzuken commented on hw1/src/me/eranik/algorithm/HashTable.java
> +        int index = table[hash].indexOf(new Data(key, null));
ну а нечего было хранить там object'ы, так всё равно никто не делает сейчас уже. когда вам расскажут про генерики, будете писать обобщённые классы, а пока вполне допустимо хранить объекты конкретных классов. ладно, пусть так будет

2017-09-25 04:57 UTC, merged