hw1-lazy
AntonYermilov/JavaHW pull request #19
Opened 2018-02-19 23:14 UTC by AntonYermilov

- Added LazyFactory implementation
- Added tests for simple and multithread implementations of Lazy interface

2018-02-24 09:08 UTC, jzuken requested changes

2018-02-24 09:08 UTC, jzuken commented on term2/hw1-lazy/src/main/java/me/eranik/util/LazyFactory.java
> +        public synchronized T get() {
ну это как-то слишком жестоко, лочить метод всегда, когда нужно залочить его только один раз в момент присваивания значения. давайте что-нибудь тут придумаем

2018-02-24 09:14 UTC, AntonYermilov commented on term2/hw1-lazy/src/main/java/me/eranik/util/LazyFactory.java
> +        public synchronized T get() {
Конкретно здесь, казалось бы, это не должно роли играть и влиять на какую-нибудь константу? :)

2018-02-28 07:33 UTC, jzuken commented on term2/hw1-lazy/src/main/java/me/eranik/util/LazyFactory.java
> +        public synchronized T get() {
ну как сказать. если оно пару раз вызовется, то да, а если много и из разных потоков, то оверхед может быть существенный

2018-02-28 07:36 UTC, jzuken requested changes

2018-02-28 07:36 UTC, jzuken commented on term2/hw1-lazy/src/main/java/me/eranik/util/LazyFactory.java
> +        private Supplier<T> supplier;
volatile забыли. 
вот тут пишут, почему без него плохо:
 https://ru.wikipedia.org/wiki/%D0%91%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%B0_%D1%81_%D0%B4%D0%B2%D0%BE%D0%B9%D0%BD%D0%BE%D0%B9_%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%BE%D0%B9

2018-02-28 19:37 UTC, AntonYermilov commented on term2/hw1-lazy/src/main/java/me/eranik/util/LazyFactory.java
> +        private Supplier<T> supplier;
Понял, справедливо... Исправил.

2018-03-07 06:43 UTC, merged