hw5-set: done
AntonYermilov/JavaHW pull request #7
Opened 2017-10-04 14:45 UTC by AntonYermilov

2017-10-07 16:10 UTC, jzuken requested changes

2017-10-07 16:10 UTC, jzuken commented on hw5-set/src/main/java/me/eranik/util/Set.java
> +    private class Node {
такие детали реализации лучше в конец класса задвигать, чтобы в начале поля и публичные штуки были

2017-10-07 16:14 UTC, AntonYermilov commented on hw5-set/src/main/java/me/eranik/util/Set.java
> +    private class Node {
Детали реализации -- это класс Node в начале исходного класса?
Или javadoc с описанием реализации класса? Разве он не должен перед классом идти?

2017-10-07 16:21 UTC, AntonYermilov commented on hw5-set/src/main/java/me/eranik/util/Set.java
> +    private class Node {
Понял, да.

2017-10-08 06:38 UTC, jzuken commented on hw5-set/src/main/java/me/eranik/util/Set.java
> +    private class Node {
это приватный класс node, да

2017-10-08 06:38 UTC, merged